const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let parks=[],filter='all',mode='visited';
const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
function size(p,max=150){return Math.max(22,Math.sqrt(p.acres/parks[0].acres)*max)}
function bubble(p,i,root,vis=false){let d=document.createElement('button');d.className='bubble';let s=size(p,vis?160:130);d.style.cssText=`width:${s}px;height:${s}px;left:${(i*29+8)%75}%;top:${(i*23+12)%67}%;background:${['#c7e96b','#ed9b61','#dce6c1','#9cc9ae'][i%4]}`;d.innerHTML=`<span>${p.name}</span><small>${fmt(p.acres)} ac</small>`;d.onclick=()=>showPark(p);root.append(d)}
function renderStage(){let set=mode==='visited'?parks.filter(p=>p.visited):parks;if(mode==='compare')set=[parks[0],parks.find(p=>p.name==='Rocky Mountain'),parks.find(p=>p.name==='Gateway Arch')];$('#field').querySelectorAll('.bubble').forEach(e=>e.remove());set.forEach((p,i)=>bubble(p,i,$('#field'),mode==='visited'));$('#stageTitle').textContent=mode==='visited'?'Our four, to scale':mode==='all'?'All 63, condensed':'The extremes, together';$('#stageCopy').textContent=mode==='visited'?'Drag a park into the field. The circle is proportional to its actual acreage.':'Every circle is scaled by land area. Try the full compare room below.';$('#caption').textContent=mode==='visited'?'Rocky Mountain is almost four times the area of Arches. Canyonlands is larger still — and Black Canyon proves drama does not require enormous acreage.':''}
function route(){let root=$('#routeCards');parks.filter(p=>p.visited).sort((a,b)=>a.name==='Black Canyon of the Gunnison'?-1:a.name.localeCompare(b.name)).forEach((p,i)=>{let e=document.createElement('article');e.className='route-card';e.style.setProperty('--tilt',`${[-1,1,-.5,1.5][i]}deg`);e.innerHTML=`<img src="${p.image}" alt="${p.name}"><span class="num">0${i+1} / ${p.state}</span><h3>${p.name}</h3><p>${fmt(p.acres)} acres</p>`;root.append(e)})}
function showPark(p){window.location.hash=p.name.toLowerCase().replaceAll(' ','-');let card=[...$('#grid').children].find(c=>c.dataset.name===p.name);if(card){card.scrollIntoView({behavior:'smooth',block:'center'});card.style.boxShadow='5px 6px 0 #cf5e3f';setTimeout(()=>card.style.boxShadow='',1400)}}
function grid(){let val=$('#search').value.toLowerCase(), sort=$('#sort').value;let list=parks.filter(p=>(filter==='all'||filter==='visited'&&p.visited||p.state===filter)&&p.name.toLowerCase().includes(val));list.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='small'?a.acres-b.acres:b.acres-a.acres);let root=$('#grid'),t=$('#card');root.innerHTML='';list.forEach(p=>{let e=t.content.cloneNode(true).firstElementChild;e.dataset.name=p.name;e.querySelector('.card-photo').style.backgroundImage=`url("${p.image}")`;e.querySelector('.state').textContent=p.visited?'✓ VISITED':p.state;e.querySelector('.rank').textContent='#'+(parks.indexOf(p)+1);e.querySelector('h3').textContent=p.name;e.querySelector('.card-area').textContent=fmt(p.acres)+' acres';e.querySelector('.bar i').style.width=Math.max(1,p.acres/parks[0].acres*100)+'%';e.querySelector('.card-desc').textContent=p.description;e.querySelector('a').href=p.wiki;root.append(e)})}
function compare(){let a=parks.find(p=>p.name==$('#parkA').value),b=parks.find(p=>p.name==$('#parkB').value),root=$('#versus');root.innerHTML='';[a,b].sort((x,y)=>y.acres-x.acres).forEach((p,i)=>{let d=document.createElement('div');d.className='vs-bubble';let s=Math.max(40,Math.sqrt(p.acres/Math.max(a.acres,b.acres))*330);d.style.cssText=`width:${s}px;height:${s}px;bottom:0;${i?'right:5%':'left:5%'};background:${i?'#ed9b61':'#c7e96b'}`;d.innerHTML=`<div><b>${p.name}</b><small>${fmt(p.acres)} acres</small></div>`;root.append(d)})}
fetch('parks.json').then(r=>r.json()).then(d=>{parks=d;$('#visitedCount').textContent=String(parks.filter(p=>p.visited).length).padStart(2,'0');route();renderStage();grid();let opts=parks.map(p=>`<option>${p.name}</option>`).join('');$('#parkA').innerHTML=opts;$('#parkB').innerHTML=opts;$('#parkA').value='Rocky Mountain';$('#parkB').value='Arches';compare();$$('.pill').forEach(b=>b.onclick=()=>{$$('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;renderStage();$('#stage').scrollIntoView({behavior:'smooth'})});$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;grid()});$('#search').oninput=grid;$('#sort').onchange=grid;$('#parkA').onchange=compare;$('#parkB').onchange=compare;});